### Apply MinMaxScaler

In [55]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn import preprocessing

wdata = load_wine(as_frame=True)

wdata.data.sample(10)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
106    12.25        1.73  2.12               19.0       80.0           1.65   
169    13.40        4.60  2.86               25.0      112.0           1.98   
161    13.69        3.26  2.54               20.0      107.0           1.83   
174    13.40        3.91  2.48               23.0      102.0           1.80   
11     14.12        1.48  2.32               16.8       95.0           2.20   
69     12.21        1.19  1.75               16.8      151.0           1.85   
156    13.84        4.12  2.38               19.5       89.0           1.80   
18     14.19        1.59  2.48               16.5      108.0           3.30   
83     13.05        3.86  2.32               22.5       85.0           1.65   
49     13.94        1.73  2.27               17.4      108.0           2.88   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
106        2.03                  0.37             1.63             3.40  1.00   
169        0.96                  0.27             1.11             8.50  0.67   
161        0.56                  0.50             0.80             5.88  0.96   
174        0.75                  0.43             1.41             7.30  0.70   
11         2.43                  0.26             1.57             5.00  1.17   
69         1.28                  0.14             2.50             2.85  1.28   
156        0.83                  0.48             1.56             9.01  0.57   
18         3.93                  0.32             1.86             8.70  1.23   
83         1.59                  0.61             1.62             4.80  0.84   
49         3.54                  0.32             2.08             8.90  1.12   

     od280/od315_of_diluted_wines  proline  
106                          3.17    510.0  
169                          1.92    630.0  
161                          1.82    680.0  
174                          1.56    750.0  
11                           2.82   1280.0  
69                           3.07    718.0  
156                          1.64    480.0  
18                           2.82   1680.0  
83                           2.01    515.0  
49                           3.10   1260.0

In [48]:
minmax_scaler = preprocessing.MinMaxScaler()
wdata.data[list(wdata.data.columns)] = minmax_scaler.fit_transform(wdata.data[list(wdata.data.columns)])

wdata.data.sample(10)

<ipython-input-48-1adbf09f3dbe>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wdata.data[list(wdata.data.columns)] = minmax_scaler.fit_transform(wdata.data[list(wdata.data.columns)])
/Users/vidita/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:2969: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc._setitem_with_indexer((slice(None), indexer), value)
/Users/vidita/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:2935: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the do

alcohol  malic_acid       ash  alcalinity_of_ash  magnesium  \
168  0.671053    0.363636  0.711230           0.716495   0.380435   
0    0.842105    0.191700  0.572193           0.257732   0.619565   
21   0.500000    0.604743  0.689840           0.412371   0.347826   
132  0.468421    0.310277  0.556150           0.690722   0.304348   
71   0.744737    0.152174  0.700535           0.742268   0.173913   
55   0.665789    0.195652  0.588235           0.510309   0.500000   
32   0.697368    0.215415  0.534759           0.340206   0.369565   
137  0.394737    0.942688  0.684492           0.742268   0.282609   
83   0.531579    0.616601  0.513369           0.613402   0.163043   
99   0.331579    0.480237  0.454545           0.381443   0.195652   

     total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
168       0.196552    0.105485              0.490566         0.356467   
0         0.627586    0.573840              0.283019         0.593060   
21        0.493103    0.436709              0.226415         0.495268   
132       0.058621    0.158228              0.264151         0.132492   
71        0.679310    0.531646              0.150943         0.460568   
55        0.682759    0.514768              0.132075         0.643533   
32        0.496552    0.495781              0.547170         0.492114   
137       0.279310    0.054852              0.943396         0.217666   
83        0.231034    0.263713              0.905660         0.381703   
99        0.644828    0.559072              0.603774         0.757098   

     color_intensity       hue  od280/od315_of_diluted_wines   proline  
168         0.629693  0.211382                      0.194139  0.336662  
0           0.372014  0.455285                      0.970696  0.561341  
21          0.274744  0.447154                      0.824176  0.350927  
132         0.377133  0.146341                      0.032967  0.201141  
71          0.179181  0.715447                      0.692308  0.094151  
55          0.424061  0.406504                      0.644689  0.600571  
32          0.218430  0.609756                      0.586081  0.507846  
137         0.317406  0.276423                      0.153846  0.169044  
83          0.300341  0.292683                      0.271062  0.169044  
99          0.087031  0.764228                      0.571429  0.091298

In [49]:
wdata.data.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean     0.518584    0.315484    0.538244           0.458502    0.323278   
std      0.213639    0.220780    0.146708           0.172142    0.155244   
min      0.000000    0.000000    0.000000           0.000000    0.000000   
25%      0.350658    0.170455    0.454545           0.340206    0.195652   
50%      0.531579    0.222332    0.534759           0.458763    0.304348   
75%      0.696711    0.462945    0.640374           0.561856    0.402174   
max      1.000000    1.000000    1.000000           1.000000    1.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        0.453487    0.356386              0.437460         0.372523   
std         0.215811    0.210730              0.234818         0.180555   
min         0.000000    0.000000              0.000000         0.000000   
25%         0.262931    0.182489              0.264151         0.264984   
50%         0.474138    0.378692              0.396226         0.361199   
75%         0.627586    0.534810              0.580189         0.485804   
max         1.000000    1.000000              1.000000         1.000000   

       color_intensity         hue  od280/od315_of_diluted_wines     proline  
count       178.000000  178.000000                    178.000000  178.000000  
mean          0.322363    0.388170                      0.491460    0.334446  
std           0.197806    0.185831                      0.260070    0.224613  
min           0.000000    0.000000                      0.000000    0.000000  
25%           0.165529    0.245935                      0.244505    0.158702  
50%           0.290956    0.394309                      0.553114    0.282097  
75%           0.419795    0.520325                      0.695971    0.504280  
max           1.000000    1.000000                      1.000000    1.000000

### Apply StandardScaler

In [51]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn import preprocessing

wdata = load_wine(as_frame=True)

standard_scaler = preprocessing.StandardScaler()
wdata.data[list(wdata.data.columns)] = standard_scaler.fit_transform(wdata.data[list(wdata.data.columns)])

wdata.data.sample(10)

<ipython-input-51-0eafe2ffbb9e>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wdata.data[list(wdata.data.columns)] = standard_scaler.fit_transform(wdata.data[list(wdata.data.columns)])
/Users/vidita/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:2969: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc._setitem_with_indexer((slice(None), indexer), value)
/Users/vidita/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:2935: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the 

alcohol  malic_acid       ash  alcalinity_of_ash  magnesium  \
15   0.777454   -0.472483  1.218995          -0.689137   0.860705   
68   0.419227   -1.253450 -0.023821          -0.749194   0.720278   
136 -0.927212    2.139716  0.634140           0.451946  -0.754202   
69  -0.976623   -1.029035 -2.253579          -0.809251   3.599025   
31   0.715690   -0.607133 -0.023821          -0.118596   0.439425   
81  -0.346638   -0.472483 -0.608676          -0.208681  -0.964842   
43   0.295700    1.475446 -0.279695          -0.599052   0.228785   
114 -1.137207   -0.849502  0.487926           0.902373  -1.105268   
175  0.332758    1.744744 -0.389355           0.151661   1.422412   
83   0.061000    1.367726 -0.170035           0.902373  -1.035055   

     total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
15        0.889114    0.884224             -0.498407        -0.229346   
68        0.376368   -0.732162              1.516045        -2.051513   
136      -1.466313   -1.565455              1.354888        -1.385721   
69       -0.713218   -0.752242             -1.787656         1.592822   
31        0.905137    1.165335             -1.143031         0.629175   
81       -0.152402    0.502717             -0.820719         0.313800   
43        0.552624    0.603113             -0.337251         0.121071   
114       0.424438    0.261765              0.549108        -0.965221   
175      -1.129824   -1.344582              0.549108        -0.422075   
83       -1.033684   -0.441012              1.999513         0.050988   

     color_intensity       hue  od280/od315_of_diluted_wines   proline  
15          0.969783  1.415139                      0.378979  1.793210  
68         -0.816731  0.274431                     -0.962842  0.009893  
136        -0.522583 -0.910151                     -1.895054 -0.085641  
69         -0.955153  1.415139                      0.647343 -0.092010  
31          0.796755  0.581544                      0.378979  2.446031  
81         -0.500955  0.888658                      0.746214 -0.104748  
43         -0.301973 -0.603037                      0.548472 -0.213021  
114        -0.933525 -0.120430                      0.816836 -1.152447  
175         2.224236 -1.612125                     -1.485445  0.280575  
83         -0.111642 -0.515290                     -0.849846 -0.738463

In [52]:
wdata.data.describe()

alcohol    malic_acid           ash  alcalinity_of_ash  \
count  1.780000e+02  1.780000e+02  1.780000e+02       1.780000e+02   
mean  -8.619821e-16 -8.357859e-17 -8.657245e-16      -1.160121e-16   
std    1.002821e+00  1.002821e+00  1.002821e+00       1.002821e+00   
min   -2.434235e+00 -1.432983e+00 -3.679162e+00      -2.671018e+00   
25%   -7.882448e-01 -6.587486e-01 -5.721225e-01      -6.891372e-01   
50%    6.099988e-02 -4.231120e-01 -2.382132e-02       1.518295e-03   
75%    8.361286e-01  6.697929e-01  6.981085e-01       6.020883e-01   
max    2.259772e+00  3.109192e+00  3.156325e+00       3.154511e+00   

          magnesium  total_phenols    flavanoids  nonflavanoid_phenols  \
count  1.780000e+02   1.780000e+02  1.780000e+02          1.780000e+02   
mean  -1.995907e-17  -2.972030e-16 -4.016762e-16          4.079134e-16   
std    1.002821e+00   1.002821e+00  1.002821e+00          1.002821e+00   
min   -2.088255e+00  -2.107246e+00 -1.695971e+00         -1.868234e+00   
25%   -8.244151e-01  -8.854682e-01 -8.275393e-01         -7.401412e-01   
50%   -1.222817e-01   9.595986e-02  1.061497e-01         -1.760948e-01   
75%    5.096384e-01   8.089974e-01  8.490851e-01          6.095413e-01   
max    4.371372e+00   2.539515e+00  3.062832e+00          2.402403e+00   

       proanthocyanins  color_intensity           hue  \
count     1.780000e+02     1.780000e+02  1.780000e+02   
mean     -1.699639e-16    -1.122697e-17  3.717376e-16   
std       1.002821e+00     1.002821e+00  1.002821e+00   
min      -2.069034e+00    -1.634288e+00 -2.094732e+00   
25%      -5.972835e-01    -7.951025e-01 -7.675624e-01   
50%      -6.289785e-02    -1.592246e-01  3.312687e-02   
75%       6.291754e-01     4.939560e-01  7.131644e-01   
max       3.485073e+00     3.435432e+00  3.301694e+00   

       od280/od315_of_diluted_wines       proline  
count                  1.780000e+02  1.780000e+02  
mean                   2.919013e-16 -7.484650e-18  
std                    1.002821e+00  1.002821e+00  
min                   -1.895054e+00 -1.493188e+00  
25%                   -9.522483e-01 -7.846378e-01  
50%                    2.377348e-01 -2.337204e-01  
75%                    7.885875e-01  7.582494e-01  
max                    1.960915e+00  2.971473e+00

### Apply PCA

In [56]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 3)

X = wdata.data.iloc[:, 1:12].values
y = wdata.data.iloc[:, 12].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


explained_variance = pca.explained_variance_ratio_

In [57]:
print(X)

[[ 1.71  2.43 15.6  ...  5.64  1.04  3.92]
 [ 1.78  2.14 11.2  ...  4.38  1.05  3.4 ]
 [ 2.36  2.67 18.6  ...  5.68  1.03  3.17]
 ...
 [ 4.28  2.26 20.   ... 10.2   0.59  1.56]
 [ 2.59  2.37 20.   ...  9.3   0.6   1.62]
 [ 4.1   2.74 24.5  ...  9.2   0.61  1.6 ]]


In [59]:
print(y)

[1065. 1050. 1185. 1480.  735. 1450. 1290. 1295. 1045. 1045. 1510. 1280.
 1320. 1150. 1547. 1310. 1280. 1130. 1680.  845.  780.  770. 1035. 1015.
  845.  830. 1195. 1285.  915. 1035. 1285. 1515.  990. 1235. 1095.  920.
  880. 1105. 1020.  760.  795. 1035. 1095.  680.  885. 1080. 1065.  985.
 1060. 1260. 1150. 1265. 1190. 1375. 1060. 1120.  970. 1270. 1285.  520.
  680.  450.  630.  420.  355.  678.  502.  510.  750.  718.  870.  410.
  472.  985.  886.  428.  392.  500.  750.  463.  278.  714.  630.  515.
  520.  450.  495.  562.  680.  625.  480.  450.  495.  290.  345.  937.
  625.  428.  660.  406.  710.  562.  438.  415.  672.  315.  510.  488.
  312.  680.  562.  325.  607.  434.  385.  407.  495.  345.  372.  564.
  625.  465.  365.  380.  380.  378.  352.  466.  342.  580.  630.  530.
  560.  600.  650.  695.  720.  515.  580.  590.  600.  780.  520.  550.
  855.  830.  415.  625.  650.  550.  500.  480.  425.  675.  640.  725.
  480.  880.  660.  620.  520.  680.  570.  675.  6

In [60]:
print(explained_variance)

[0.90733129 0.05423592 0.02615831]
